[package]
name = "archive-util"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
flate2 = "1.1.8"
glob = "0.3.3"
normalize-path = "0.2.1"
tar = "0.4.44"
walkdir = "2.5.0"
xz2 = "0.1.7"
zip = "7.0.0"
