name: Alternative

on:
  push:
    branches: ["main"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "main"
  cancel-in-progress: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ github.token }}
  EZIP_VERSION: 0.0.2

jobs:
  pkg_github_cli:
    name: Github CLI
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/pkg_github_cli.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_github_cli
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1

  pkg_deno_cli:
    name: Deno
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/pkg_deno.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_deno
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1


