name: Alternative

on:
  push:
    branches: ["main"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "main"
  cancel-in-progress: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ github.token }}
  EZIP_VERSION: 0.0.2

jobs:
  pkg_gh:
    name: gh
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/pkg_gh.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_gh
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1

  pkg_deno:
    name: deno
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/pkg_deno.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_deno
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1

  pkg_8zip:
    name: 8zip
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/pkg_8zip.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_8zip
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1

  pkg_fnm:
    name: fnm
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/pkg_fnm.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_fnm
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1

  pkg_node:
    name: node
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: wget https://github.com/denoland/deno/releases/latest/download/deno-aarch64-unknown-linux-gnu.zip -O /tmp/deno.zip && unzip /tmp/deno.zip -d /usr/local/bin
      - run: bash ./scripts/pkg_node.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_node
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1


