name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "main"
  cancel-in-progress: false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ github.token }}
  EZIP_VERSION: 0.0.2

jobs:
  pkg_gh:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_deno:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_8zip:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_fnm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_hyperfine:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_node:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: wget https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip -O /tmp/deno.zip && unzip /tmp/deno.zip -d /usr/local/bin
      - run: deno install
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_just:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_python:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: wget https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip -O /tmp/deno.zip && unzip /tmp/deno.zip -d /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_go:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_terraform:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1
  pkg_vultr:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - run: curl -L https://github.com/alshdavid/8zip/releases/download/$EZIP_VERSION/8zip-linux-amd64.tar.gz | tar -xzf - -C /usr/local/bin
      - run: bash ./scripts/${{ github.job }}.bash
      - uses: actions/upload-artifact@v6
        with:
          name: binaries_${{ github.job }}
          path: ${{ github.workspace }}/binaries/**/*
          if-no-files-found: warn
          retention-days: 1

  publish-github-release:
    name: "ðŸ”„ Publish Github Release"
    runs-on: ubuntu-24.04
    needs:
      - pkg_gh
      - pkg_deno
      - pkg_8zip
      - pkg_fnm
      - pkg_node
      - pkg_hyperfine
      - pkg_just
      - pkg_python
      - pkg_go
      - pkg_terraform
      - pkg_vultr
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        with: 
          path: binaries
          merge-multiple: true
      # Install Deno
      - run: wget https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip -O /tmp/deno.zip && unzip /tmp/deno.zip -d /usr/local/bin
      # Generate release
      - run: deno install
      - run: deno -A ./site/cmd/generate-release.mts --run

  publish-pages:
    name: "ðŸ“ƒ Publish Pages"
    runs-on: ubuntu-24.04
    needs:
      - publish-github-release
    steps:
      - uses: actions/checkout@v6
      - uses: actions/configure-pages@v5
      # Install Deno
      - run: wget https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip -O /tmp/deno.zip && unzip /tmp/deno.zip -d /usr/local/bin
      # Generate pages
      - run: deno install
      - run: deno -A ./site/cmd/generate-package-index.mts --run
      - run: deno -A ./site/cmd/copy-files.mts --run
      - run: deno -A ./site/cmd/build-shell-scripts.mts --run
      - run: deno -A ./site/cmd/build-page.mts --run
      - uses: actions/upload-pages-artifact@v3
        with: { path: 'dist' }
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  

