name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

defaults:
  run:
    shell: bash

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 'latest'
      # - run: eval $(curl -sSf "sh.davidalsh.com/nodejs.sh" | sh -s)
      - run: npm install
      - run: node ./site/main.mts
        env:
          GH_TOKEN: ${{ github.token }}
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/upload-pages-artifact@v3
        with: { path: 'dist' }
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  # test-linux:
  #   runs-on: 'ubuntu-latest'
  #   needs: [deploy]
  #   steps:
  #       - run: eval $(curl -sSf "sh.davidalsh.com/go.sh" | sh)
  #       - run: which go
  #       - run: go version

  #       - run: eval $(curl -sSf "sh.davidalsh.com/just.sh" | sh)
  #       - run: which just
  #       - run: just --version

  #       - run: eval $(curl -sSf "sh.davidalsh.com/nodejs.sh" | sh)
  #       - run: which node
  #       - run: node --version 
        
  #       - run: eval $(curl -sSf "sh.davidalsh.com/rrm.sh" | sh)
  #       - run: which rrm
  #       - run: rrm --help

  #       - run: eval $(curl -sSf "sh.davidalsh.com/http-server-rs.sh" | sh)
  #       - run: which http-server-rs
  #       - run: http-server-rs --help

  #       - run: eval $(curl -sSf "sh.davidalsh.com/rust.sh" | sh)
  #       - run: which cargo
  #       - run: cargo --version

  #       - run: eval $(curl -sSf "sh.davidalsh.com/which-platform.sh" | sh)
  #       - run: echo $OS_ARCH

  #       - run: eval $(curl -sSf "sh.davidalsh.com/which-platform.sh" | sh -s - --version 3.12)
  #       - run: which python
  #       - run: python --version

  # test-windows:
  #   runs-on: 'windows-latest'
  #   needs: [deploy]
  #   steps:
  #       - run: eval $(curl -sSf "sh.davidalsh.com/go.sh" | sh)
  #       - run: which go
  #       - run: go version

  #       - run: eval $(curl -sSf "sh.davidalsh.com/just.sh" | sh)
  #       - run: which just
  #       - run: just --version

  #       - run: eval $(curl -sSf "sh.davidalsh.com/nodejs.sh" | sh)
  #       - run: which node
  #       - run: node --version 
        
  #       - run: eval $(curl -sSf "sh.davidalsh.com/procmon.sh" | sh)
  #       - run: which procmon
  #       - run: procmon --help

  #       - run: eval $(curl -sSf "sh.davidalsh.com/rrm.sh" | sh)
  #       - run: which rrm
  #       - run: rrm --help

  #       - run: eval $(curl -sSf "sh.davidalsh.com/rust.sh" | sh)
  #       - run: which cargo
  #       - run: cargo --version

  #       - run: eval $(curl -sSf "sh.davidalsh.com/which-platform.sh" | sh)
  #       - run: echo $OS_ARCH

  #       - run: |
  #           eval $(curl -sSf "sh.davidalsh.com/uutils.sh" | sh)
  #           where coreutils
  #       - run: ls $HOME/.local/uutils
  #       - run: where coreutils
  #       - run: where rm
  #       - shell: pwsh
  #         run: |
  #           Remove-Item Alias:"rm"
  #           Get-Command rm



